CREATE TABLE MEMBER(
    MID NVARCHAR2(20) PRIMARY KEY,
    MPASSWORD NVARCHAR2(20),
    MNAME NVARCHAR2(20),
    MBIRTH DATE,
    MEMAIL NVARCHAR2(20),
    MADDRESS1 NVARCHAR2(60),
    MADDRESS2 NVARCHAR2(60),
    MADDRESS3 NVARCHAR2(60),
    MADDRESS4 NVARCHAR2(60),
    MPHONE NVARCHAR2(20),
    MPHOTO NVARCHAR2(60)
);
ALTER TABLE MEMBER ADD KAKAOID NVARCHAR2(30); 
ALTER TABLE MEMBER ADD NAVERID NVARCHAR2(30); 
DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP TABLE REPLY;
CREATE TABLE BOARD(
    BNUMBER NUMBER PRIMARY KEY,
    BWRITER NVARCHAR2(20) REFERENCES MEMBER(MID)
    ON DELETE CASCADE,
    BTITLE NVARCHAR2(20),
    BCONTENTS NVARCHAR2(300),
    BDATE DATE,
    BHITS NUMBER,
    BFILENAME NVARCHAR2(60)
);

CREATE TABLE REPLY(
    CNUMBER NUMBER PRIMARY KEY,
    CBNUMBER NUMBER REFERENCES BOARD(BNUMBER)
    ON DELETE CASCADE,
    REPLY NVARCHAR2(50),
    REPLYER NVARCHAR2(20) REFERENCES MEMBER(MID)
    ON DELETE CASCADE,
    RDATE DATE
    
);
CREATE SEQUENCE BNUM_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
COMMIT;
CREATE SEQUENCE CNUMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
    
DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP TABLE REPLY;
SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM REPLY;